default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

# Development points at its dedicated cache database (created by db:prepare)
# so switching config.cache_store to :solid_cache_store just works.
development:
  database: cache
  <<: *default

test:
  <<: *default

production:
  database: cache
  <<: *default
